# This workflow will be triggered on every commit merge to the defined branch. It involves
# 1. Checking if an AsyncAPI spec file is present in the commit
# 2. Import the AsyncAPI spec file to Solace PubSub+ Event Portal
# 3. Trigger a github workflow at a target infrastructure repo to run provisioning and configuration

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# To get started, configure the following in your repos secrets https://docs.github.com/en/actions/security-guides/encrypted-secrets
# CLI_SOLACE_CLOUD_TOKEN: your Solace Cloud Token
# INFRA_REPO: the infrastructure repo in the form of <github_user>/<repo_name>
# WORKFLOW_PAT: Personal Access Token token for the destination repo for authentication. See more here https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
## Note: The PAT should have workflow access enabled

name: Import AsyncAPI to Solace PubSub+ Event Portal
on:
  push: 
    branches: [ main ]

jobs:
  asyncapi-present:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current Branch
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
            
      - name: Install asycnapi cli
        run: npm install -g @asyncapi/cli@0.24.0 
          
    # Get all files in commit
      - id: files
        uses: jitterbit/get-changed-files@v1

      - name: Check if an AsycnAPI file is in commit
        run: |
          asyncapiFiles=()
          for changed_file in ${{ steps.files.outputs.all }}
          do
            if [[ ( ${changed_file} == *.yaml ) || ( ${changed_file} == *.yml ) || ( ${changed_file} == *.json ) ]]
            then
              asyncapi validate ${changed_file} &> check.txt
              # Check if the file is an asyncapi spec
              if ! grep -q "field is missing." check.txt; then
                asyncapiFiles+=("$changed_file")
                echo "ASYNCAPI_FILE_PATH=${changed_file}" >> $GITHUB_ENV
              fi
            fi
          done
          if [ ${#asyncapiFiles[@]} -eq 0 ]; then
            echo "Cancel workflow. No file found!"
            echo "CANCEL_WORKFLOW=true" >> $GITHUB_ENV
          fi

      - name: Cancel Workflow if no asyncAPI file present in PR
        if: env.CANCEL_WORKFLOW == 'true'
        uses: andymckay/cancel-action@0.3
        with:
          token: ${{ secrets.WORKFLOW_PAT }}
      
      - id: set-async-path-var
        run: echo "ASYNCAPI_FILE_PATH=${{env.ASYNCAPI_FILE_PATH}}" >> $GITHUB_OUTPUT 
        
    outputs:
      ASYNCAPI_FILE_PATH: ${{steps.set-async-path-var.outputs.ASYNCAPI_FILE_PATH}}

  import-asyncapi-file:
    needs: asyncapi-present
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current Branch
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: Import AsyncAPI spec file to EP
        env:
          CLI_SOLACE_CLOUD_TOKEN: ${{ secrets.CLI_SOLACE_CLOUD_TOKEN }}
          CLI_IMPORT_CREATE_API_APPLICATION: true
        run: |
          npx @solace-labs/ep-async-api-importer -fp ./${{needs.asyncapi-present.outputs.ASYNCAPI_FILE_PATH}}

  Trigger-Generate-Implementations-Configuration:
    needs: asyncapi-present
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current Branch
        uses: actions/checkout@master

      - name: Trigger generate implementation 
        run: |
          # Read AsyncAPI Spec file into variable
          spec=`cat ${{needs.asyncapi-present.outputs.ASYNCAPI_FILE_PATH}} | base64 -w 0`
          curl -X POST -u "${{ github.actor }}:${{ secrets.WORKFLOW_PAT }}" \
            -H "Accept: application/vnd.github.everest-preview+json"  \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/${{ secrets.INFRA_REPO }}/dispatches \
            --data "{\"event_type\":\"trigger-event\",\"client_payload\":{\"asyncapi\":\"$spec\"}}"
  